### ISSUE TITLE
ci: add brew continuous deployment with a github action

### ISSUE THREAD

**Issue by vmarchese** [jrnd-io/jr#165]
Add brew CD with a github actions on release publish 

Useful links: 
- https://extrawurst.medium.com/github-actions-homebrew-%EF%B8%8F-2789ae5023fd
- https://github.com/marketplace/actions/homebrew-bump-formula

**Comment by ram-pi** [comment]
The workflow has been added and we are currently on the [autobump](https://github.com/Homebrew/homebrew-core/blob/master/.github/autobump.txt) brew list (this means that the workflow shouldn't be necessary).
